#!/bin/bash

NODERUN="noderun"
INIT="init"
declare Path="";

function MoveFiles(){

    cp $1 $Path$1       
}

function Validation(){

    TOOL=$1

    if ! [ -x "$(command -v $TOOL)" ]; then
        echo Installing $TOOL...;
        return 1;
    else
        echo Already have $TOOL nice!;
        return 0;
    fi
}

function MakeExecutable(){
    chmod +xwr $1
}

function GetOS(){

    declare OSTYPE=$(uname)

    if [[ $OSTYPE -eq "Linux-gnu" ]]
    then
        Path="/usr/local/bin/"
    elif [[ $OSTYPE -eq "Darwin" ]] 
    then
        Path="/usr/local/bin/"
    elif [[ $OSTYPE -eq "Cygwin" ]]
    then
        echo Null
        exit        
    else
        echo Unknow OS
        exit
    fi
}

GetOS
MakeExecutable $NODERUN
MakeExecutable $INIT

MoveFiles $NODERUN

Validation node

RT1=$?
if [ $RT1 -eq 1 ]
then
    curl "https://nodejs.org/dist/v16.17.1/node-v16.17.1.tar.gz" > node.tar.gz
    tar -xvf node.tar.gz
    rm -rf node.tar.gz
fi

Validation npm

RT2=$?
if [ $RT2 -eq 1 ]
then
    npm install -g npm
fi

rm -rf ./$NODERUN
rm -rf ./$INIT

